version: "3.8"

services:
  ##############################################################################
  pg:
    image: postgres:13.3-alpine
    restart: "no"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
  ##############################################################################
  redis:
    image: redis:6.2.5-alpine
    restart: "no"
    ports:
      - 6379:6379
  ##############################################################################
  jaeger:
    image: jaegertracing/all-in-one:1.25.0
    restart: "no"
    ports:
      - 14268:14268 # accept jaeger.thrift directly from clients
      - 16686:16686 # serve frontend
